stages
  - build
  - test

job1:
  stage: build
  script:
    - echo "build Docker Image"
    - docker build . -t 1.0
job2:     
  test:pylint:
      image: python:3.6
      script:
          - echo "Pylint test"    
          - pip install pylint --quiet
          - pylint --ignored-classes=_socketobject *.py
  test:pytest: 
    image: python:3.6
    script:
      - echo "Pytest"       
      - pip install pytest --quiet
      - pytest          
